### PR TITLE
Inspiration from riscv-basics.com

### PR DESCRIPTION
**Pull request by NatoBoram**
I essentially replied to riscv-basics.com's bullshit. Some of it might need some more juice, like `Large, Supportive Ecosystem`. Please contribute to this one, or change it entirely!

### CODE REVIEW

**Comment by NatoBoram** [comment]
@arm-facts If you can enable issues, that'd be great. This would give good ideas for future contributors to send PRs.

**Comment by arm-facts** [comment]
@NatoBoram Issues module has been enabled, thanks.

**Comment by arm-facts** [comment]
@NatoBoram I also applied the cc-by-sa license, is that OK for you?

**Comment by NatoBoram** [comment]
100% okay!

**Pull request merged**
